(()=>{'use strict';
const DATA_URL='https://raw.githubusercontent.com/jensbaagaard/poker-practice/main/data/openSourcePokerData/MTT_40_GTO.json';
const POS=['LJ','HJ','CO','BTN','SB','BB'];
const R=['A','K','Q','J','T','9','8','7','6','5','4','3','2'];
const POSTFLOP_RANK={SB:0,BB:1,LJ:2,HJ:3,CO:4,BTN:5};
let ranges=null,S=null;
let selectedPos='LJ',selectedEvent=null,selectedPending=null,selectedAction='open';
const clamp=v=>Math.max(0,Math.min(1,v));
const rv=(k,h)=>ranges&&ranges[k]?Number(ranges[k][h]||0):0;
const fmt=n=>`${Number(Number(n).toFixed(1))}BB`;
const openSize=p=>p==='SB'?3.5:2.3;
function threeSize(p,opener,size){const ip=POSTFLOP_RANK[p]>POSTFLOP_RANK[opener],v=size*(ip?3:4);return Math.min(v,ip?9:10)}
function hand(r,c){if(r===c)return r+r;return R.indexOf(r)<R.indexOf(c)?r+c+'s':c+r+'o'}
function fresh(){return{stage:0,opener:null,three:null,four:null,openSize:null,threeSize:null,limpers:[],callers:[],folded:new Set(),queue:POS.slice(),history:[],pending:{},done:false}}
function snapshot(){return{stage:S.stage,opener:S.opener,three:S.three,four:S.four,openSize:S.openSize,threeSize:S.threeSize,limpers:[...S.limpers],callers:[...S.callers]}}
function circularAfter(p){const i=POS.indexOf(p);return POS.slice(i+1).concat(POS.slice(0,i))}
function eventsFor(p){return S.history.map((e,i)=>({...e,index:i})).filter(e=>e.pos===p)}
function nonFoldedPastActors(raiser){return POS.filter(p=>p!==raiser&&!S.folded.has(p)&&eventsFor(p).some(e=>e.action!=='fold'))}
function defaultAction(opts){for(const a of ['open','3bet','4bet','call','check','fold','limp'])if(opts.some(x=>x[0]===a))return a;return opts[0]?.[0]||'fold'}
function actionOptions(p,ctx){if(ctx.stage===0){if(p==='BB'&&ctx.limpers.length===0)return[['check','Check'],['open',`Open ${fmt(openSize(p))}`]];return[['fold','Fold'],['limp','Limp'],['open',`Open ${fmt(openSize(p))}`]]}if(ctx.stage===1){const t=threeSize(p,ctx.opener,ctx.openSize);return[['fold','Fold'],['call','Call'],['3bet',`3bet ${fmt(t)}`]]}if(ctx.stage===2)return[['fold','Fold'],['call','Call'],['4bet','4bet all-in 40BB']];return[['fold','Fold'],['call','Call']]}
function actionLabel(a,p,ctx){const m=Object.fromEntries(actionOptions(p,ctx));return m[a]||a}
function rangeInfo(p,a,ctx){if(!ranges)return null;const values={};let title='';if(ctx.stage===0){if(ctx.limpers.length)return null;for(const r of R)for(const c of R){const h=hand(r,c),o=rv('Open'+p,h),l=rv('Limp'+p,h);let v=null;if(a==='open'){v=o;title=`${p} Open ${fmt(openSize(p))}`}else if(a==='limp'){v=l;title=`${p} Limp`}else if(a==='fold'||a==='check'){v=1-o-l;title=`${p} ${a==='check'?'Check':'Fold'}`}if(v!==null)values[h]=clamp(v)}}else if(ctx.stage===1){if(ctx.callers.length)return null;for(const r of R)for(const c of R){const h=hand(r,c),t=rv(`3Bet${p}vs${ctx.opener}`,h),ca=rv(`Call${p}vs${ctx.opener}`,h);let v=null;if(a==='3bet'){v=t;title=`${p} 3bet ${fmt(threeSize(p,ctx.opener,ctx.openSize))} vs ${ctx.opener}`}else if(a==='call'){v=ca;title=`${p} Call vs ${ctx.opener}`}else if(a==='fold'){v=1-t-ca;title=`${p} Fold vs ${ctx.opener}`}if(v!==null)values[h]=clamp(v)}}else if(ctx.stage===2&&p===ctx.opener){for(const r of R)for(const c of R){const h=hand(r,c),base=rv('Open'+p,h),b4=rv(`4Bet${p}vs${ctx.three}`,h),ca=rv(`Call 3Bet${p}vs${ctx.three}`,h);let v=null;if(base<=1e-9)v=0;else if(a==='4bet'){v=b4/base;title=`${p} 4bet all-in vs ${ctx.three}`}else if(a==='call'){v=ca/base;title=`${p} Call 3bet vs ${ctx.three}`}else if(a==='fold'){v=(base-b4-ca)/base;title=`${p} Fold vs ${ctx.three} 3bet`}if(v!==null)values[h]=clamp(v)}}else if(ctx.stage>=3&&p===ctx.three){for(const r of R)for(const c of R){const h=hand(r,c),base=rv(`3Bet${p}vs${ctx.opener}`,h),ca=rv(`Call 4Bet${p}vs${ctx.opener}`,h);let v=null;if(base<=1e-9)v=0;else if(a==='call'){v=ca/base;title=`${p} Call 4bet vs ${ctx.opener}`}else if(a==='fold'){v=(base-ca)/base;title=`${p} Fold vs ${ctx.opener} 4bet`}if(v!==null)values[h]=clamp(v)}}return Object.keys(values).length?{title,values}:null}
function unsupportedText(p,ctx){if(ctx.stage===0&&ctx.limpers.length)return'前にLimpがある局面のレンジは、この公開データにはありません。';if(ctx.stage===1&&ctx.callers.length)return'すでにCallが入ったmultiway局面のレンジは、この公開データにはありません。';if(ctx.stage===2&&p!==ctx.opener)return'cold 4bet / cold call のレンジは、この公開データにはありません。';if(ctx.stage>=3&&p!==ctx.three)return'この4betに対するレンジは、この公開データにはありません。';return'このアクション履歴に直接対応する公開レンジデータはありません。'}
function markPendingAfterRaise(raiser){const ctx=snapshot();for(const p of nonFoldedPastActors(raiser)){const n=eventsFor(p).length+1;S.pending[p]={ctx:{...ctx,limpers:[...ctx.limpers],callers:[...ctx.callers]},number:n}}}
function applyCore(a){if(S.done||!S.queue.length)return false;const p=S.queue[0],ctx=snapshot(),opts=actionOptions(p,ctx);if(!opts.some(x=>x[0]===a))return false;S.history.push({pos:p,action:a,ctx});delete S.pending[p];let aggressive=false;if(a==='fold')S.folded.add(p);else if(a==='limp')S.limpers.push(p);else if(a==='call')S.callers.push(p);else if(a==='open'){S.stage=1;S.opener=p;S.openSize=openSize(p);S.callers=[];aggressive=true}else if(a==='3bet'){S.stage=2;S.three=p;S.threeSize=threeSize(p,S.opener,S.openSize);S.callers=[];aggressive=true}else if(a==='4bet'){S.stage=3;S.four=p;S.callers=[];aggressive=true}if([...S.folded].length>=5){S.queue=[];S.done=true}else if(aggressive){S.queue=circularAfter(p).filter(q=>q!==p&&!S.folded.has(q));markPendingAfterRaise(p)}else S.queue.shift();if(!S.queue.length)S.done=true;return true}
function applyAction(a){if(!applyCore(a))return;const p=S.queue[0]||S.history[S.history.length-1].pos;selectedPos=p;selectedEvent=null;selectedPending=null;if(S.queue.length)selectedAction=defaultAction(actionOptions(S.queue[0],snapshot()));else selectedAction=a;render()}
function editHistory(index,a){const old=S.history.map(e=>e.action);old[index]=a;S=fresh();for(let i=0;i<=index;i++){if(!applyCore(old[i]))break}selectedEvent=null;selectedPending=null;selectedPos=S.queue[0]||S.history[S.history.length-1]?.pos||'LJ';selectedAction=S.queue.length?defaultAction(actionOptions(S.queue[0],snapshot())):'fold';render()}
function selectPosition(p){selectedPos=p;selectedEvent=null;selectedPending=null;if(S.pending[p]){selectedPending=p;selectedAction=defaultAction(actionOptions(p,S.pending[p].ctx))}else if(S.queue[0]===p&&!S.done)selectedAction=defaultAction(actionOptions(p,snapshot()));else{const evs=eventsFor(p);if(evs.length){selectedEvent=evs[evs.length-1].index;selectedAction=evs[evs.length-1].action}}render()}
function currentDecision(){if(!S)return null;if(selectedPending&&S.pending[selectedPending])return{pos:selectedPending,ctx:S.pending[selectedPending].ctx,chosen:null,historical:false,pending:true};if(selectedEvent!==null){const e=S.history[selectedEvent];return e?{pos:e.pos,ctx:e.ctx,chosen:e.action,historical:true}:null}if(!S.done&&S.queue[0]===selectedPos)return{pos:selectedPos,ctx:snapshot(),chosen:null,historical:false};const evs=eventsFor(selectedPos);if(evs.length){const e=evs[evs.length-1];return{pos:e.pos,ctx:e.ctx,chosen:e.action,historical:true}}return null}
function grid(info){if(!info)return'';let html='<div class="custom-range-grid">';for(const r of R)for(const c of R){const h=hand(r,c),v=clamp(info.values[h]||0),pct=Math.round(v*1000)/10;html+=`<div class="custom-range-cell" style="background:linear-gradient(to right,#a9ee61 0%,#a9ee61 ${v*100}%,#39433f ${v*100}%,#39433f 100%)"><div class="custom-hand">${h}</div><div class="custom-pct">${pct}%</div></div>`}return html+'</div>'}
function selectHtml(opts,value,attrs,placeholder){return`<select class="custom-action-select" ${attrs}><option value="">${placeholder}</option>${opts.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`}
function rowHtml(p){const evs=eventsFor(p),current=!S.done&&S.queue[0]===p,pending=S.pending[p];let lines='';for(const e of evs){const opts=actionOptions(p,e.ctx);lines+=selectHtml(opts,e.action,`data-history="${e.index}"`,`${e.index===0?'1':eventsFor(p).findIndex(x=>x.index===e.index)+1}回目のアクション`)}if(pending){const opts=actionOptions(p,pending.ctx),enabled=current?'':'disabled';lines+=selectHtml(opts,'',`data-pending-select="${p}" ${enabled}`,`${pending.number}回目のアクション`)}else if(current){const opts=actionOptions(p,snapshot());lines+=selectHtml(opts,'',`data-current="${p}"`,'アクションを選択')}return`<div class="custom-row ${selectedPos===p?'selected':''}" data-row="${p}"><div class="custom-pos" data-pos="${p}">${p}</div><div class="custom-action-stack">${lines||''}</div></div>`}
function render(){const seq=document.getElementById('customSequence2');if(!seq||!S)return;seq.innerHTML=POS.map(rowHtml).join('');seq.querySelectorAll('.custom-pos').forEach(e=>e.onclick=()=>selectPosition(e.dataset.pos));seq.querySelectorAll('[data-history]').forEach(e=>e.onchange=()=>{if(e.value)editHistory(Number(e.dataset.history),e.value)});seq.querySelectorAll('[data-current]').forEach(e=>e.onchange=()=>{if(e.value)applyAction(e.value)});seq.querySelectorAll('[data-pending-select]').forEach(e=>{e.onclick=()=>{selectedPos=e.dataset.pendingSelect;selectedEvent=null;selectedPending=e.dataset.pendingSelect;selectedAction=defaultAction(actionOptions(selectedPos,S.pending[selectedPos].ctx));render()};e.onchange=()=>{if(e.value&&S.queue[0]===e.dataset.pendingSelect)applyAction(e.value)}});const title=document.getElementById('customTitle2'),context=document.getElementById('customContext2'),tabs=document.getElementById('customActionTabs2'),range=document.getElementById('customRange2'),summary=document.getElementById('customSummary2');title.textContent=`${selectedPos} HAND RANGE`;summary.innerHTML='';const d=currentDecision();if(!d){tabs.innerHTML='';range.innerHTML='<div class="custom-unsupported">前のプレイヤーのアクションを選択してください</div>';context.textContent='';return}const opts=actionOptions(d.pos,d.ctx);if(!opts.some(x=>x[0]===selectedAction))selectedAction=d.chosen||defaultAction(opts);context.textContent=(d.pending?'次のアクション · ':'')+(d.ctx.stage===0?'Unopened pot':d.ctx.stage===1?`${d.ctx.opener} Open ${fmt(d.ctx.openSize)} に対する ${d.pos} の戦略`:d.ctx.stage===2?`${d.ctx.three} 3bet ${fmt(d.ctx.threeSize)} に対する ${d.pos} の戦略`:`${d.ctx.four} 4bet all-in に対する ${d.pos} の戦略`);tabs.innerHTML=opts.map(([a,l])=>`<button class="custom-action-btn ${selectedAction===a?'active':''}" data-a="${a}">${l}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedAction=b.dataset.a;render()});const info=rangeInfo(d.pos,selectedAction,d.ctx);if(info){range.innerHTML=grid(info);summary.innerHTML=`<strong>${info.title}</strong><div class="custom-muted">各セルは、そのハンドでこのアクションを選ぶ頻度です。</div>`}else range.innerHTML=`<div class="custom-unsupported">${unsupportedText(d.pos,d.ctx)}</div>`}
function inject(){const app=document.querySelector('.app'),header=app&&app.querySelector('header');if(!app||!header||document.getElementById('customTab'))return;header.style.justifyContent='space-between';const tabs=document.createElement('div');tabs.className='mode-tabs';tabs.innerHTML='<button class="mode-tab active" id="gameTab2">GAME</button><button class="mode-tab" id="customTab">CUSTOM</button>';header.appendChild(tabs);const gameNodes=[...app.children].filter(x=>x!==header);const wrap=document.createElement('div');wrap.id='gameMode2';for(const n of gameNodes)wrap.appendChild(n);app.appendChild(wrap);const custom=document.createElement('section');custom.id='customMode2';custom.hidden=true;custom.innerHTML='<section class="custom-mode-panel"><div><h2 style="font-size:13px;letter-spacing:.11em;margin:0">CUSTOM MODE</h2><div class="custom-muted">LJから順にアクションを指定します。選択済みのアクションもプルダウンから変更できます。</div></div><div class="custom-grid"><div><div class="custom-sequence" id="customSequence2"></div><button class="custom-reset" id="customReset2">リセット</button></div><div><h2 id="customTitle2" style="font-size:13px;letter-spacing:.11em;margin:0">LJ HAND RANGE</h2><div class="custom-muted" id="customContext2"></div><div class="custom-toolbar" id="customActionTabs2"></div><div class="custom-range-wrap" id="customRange2"></div><div class="custom-summary" id="customSummary2"></div></div></div></section>';app.appendChild(custom);document.getElementById('gameTab2').onclick=()=>setMode(false);document.getElementById('customTab').onclick=()=>setMode(true);document.getElementById('customReset2').onclick=reset}
function setMode(custom){document.getElementById('gameMode2').hidden=custom;document.getElementById('customMode2').hidden=!custom;document.getElementById('gameTab2').classList.toggle('active',!custom);document.getElementById('customTab').classList.toggle('active',custom);if(custom)render()}
function reset(){S=fresh();selectedPos='LJ';selectedEvent=null;selectedPending=null;selectedAction='open';render()}
function boot(){inject();S=fresh();fetch(DATA_URL).then(r=>r.ok?r.json():Promise.reject()).then(x=>{ranges=x;render()}).catch(()=>render())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();