(()=>{'use strict';
const DATA_URL='https://raw.githubusercontent.com/jensbaagaard/poker-practice/main/data/openSourcePokerData/MTT_40_GTO.json';
const POS=['LJ','HJ','CO','BTN','SB','BB'];
const R=['A','K','Q','J','T','9','8','7','6','5','4','3','2'];
const POSTFLOP_RANK={SB:0,BB:1,LJ:2,HJ:3,CO:4,BTN:5};
let ranges=null;
let first={},second={};
let selected={type:'first',pos:'LJ'};
let selectedAction='open';
const clamp=v=>Math.max(0,Math.min(1,v));
const rv=(k,h)=>ranges&&ranges[k]?Number(ranges[k][h]||0):0;
const fmt=n=>`${Number(Number(n).toFixed(1))}BB`;
const openSize=p=>p==='SB'?3.5:2.3;
function threeSize(p,opener,size){const ip=POSTFLOP_RANK[p]>POSTFLOP_RANK[opener],v=size*(ip?3:4);return Math.min(v,ip?9:10)}
function hand(r,c){if(r===c)return r+r;return R.indexOf(r)<R.indexOf(c)?r+c+'s':c+r+'o'}
function blank(){first=Object.fromEntries(POS.map(p=>[p,'']));second=Object.fromEntries(POS.map(p=>[p,'']))}
function baseCtx(){return{stage:0,opener:null,three:null,four:null,openSize:null,threeSize:null,callers:[]}}
function cloneCtx(c){return{stage:c.stage,opener:c.opener,three:c.three,four:c.four,openSize:c.openSize,threeSize:c.threeSize,callers:[...c.callers]}}
function actionOptions(p,ctx){if(ctx.stage===0)return[['fold','Fold'],['open',`Open ${fmt(openSize(p))}`]];if(ctx.stage===1){const t=threeSize(p,ctx.opener,ctx.openSize);return[['fold','Fold'],['call','Call'],['3bet',`3bet ${fmt(t)}`]]}if(ctx.stage===2)return[['fold','Fold'],['call','Call'],['4bet','4bet all-in 40BB']];return[['fold','Fold'],['call','Call']]}
function labelFor(a,p,ctx){const hit=actionOptions(p,ctx).find(x=>x[0]===a);return hit?hit[1]:({fold:'Fold',open:`Open ${fmt(openSize(p))}`,call:'Call','3bet':'3bet','4bet':'4bet all-in 40BB'})[a]||a}
function applyToCtx(ctx,p,a){const n=cloneCtx(ctx);if(a==='fold')return n;if(a==='call'){n.callers.push(p);return n}if(a==='open'){n.stage=1;n.opener=p;n.openSize=openSize(p);n.callers=[];return n}if(a==='3bet'){n.stage=2;n.three=p;n.threeSize=threeSize(p,n.opener,n.openSize);n.callers=[];return n}if(a==='4bet'){n.stage=3;n.four=p;n.callers=[];return n}return n}
function derive(){let ctx=baseCtx(),blocked=false;const decisions={};for(const p of POS){if(blocked){decisions[p]={ctx:null,opts:[],value:first[p],valid:false};continue}const here=cloneCtx(ctx),opts=actionOptions(p,here),value=first[p],valid=!value||opts.some(x=>x[0]===value);decisions[p]={ctx:here,opts,value,valid};if(!value||!valid){blocked=true;continue}ctx=applyToCtx(ctx,p,value)}
 const responses={};if(ctx.stage===2&&ctx.opener&&ctx.three){responses[ctx.opener]={ctx:cloneCtx(ctx),opts:actionOptions(ctx.opener,ctx),value:second[ctx.opener]||'',valid:true,number:2};const a=second[ctx.opener];if(a&&actionOptions(ctx.opener,ctx).some(x=>x[0]===a)){const after=applyToCtx(ctx,ctx.opener,a);if(a==='4bet'&&after.three){responses[after.three]={ctx:cloneCtx(after),opts:actionOptions(after.three,after),value:second[after.three]||'',valid:true,number:2}}}
 }else if(ctx.stage>=3&&ctx.three){responses[ctx.three]={ctx:cloneCtx(ctx),opts:actionOptions(ctx.three,ctx),value:second[ctx.three]||'',valid:true,number:2}}
 return{decisions,responses,finalCtx:ctx}}
function rangeInfo(p,a,ctx){if(!ranges||!ctx)return null;const values={};let title='';if(ctx.stage===0){for(const r of R)for(const c of R){const h=hand(r,c),o=rv('Open'+p,h);let v=null;if(a==='open'){v=o;title=`${p} Open ${fmt(openSize(p))}`}else if(a==='fold'){v=1-o;title=`${p} Fold`}if(v!==null)values[h]=clamp(v)}}else if(ctx.stage===1){if(ctx.callers.length)return null;for(const r of R)for(const c of R){const h=hand(r,c),t=rv(`3Bet${p}vs${ctx.opener}`,h),ca=rv(`Call${p}vs${ctx.opener}`,h);let v=null;if(a==='3bet'){v=t;title=`${p} 3bet ${fmt(threeSize(p,ctx.opener,ctx.openSize))} vs ${ctx.opener}`}else if(a==='call'){v=ca;title=`${p} Call vs ${ctx.opener}`}else if(a==='fold'){v=1-t-ca;title=`${p} Fold vs ${ctx.opener}`}if(v!==null)values[h]=clamp(v)}}else if(ctx.stage===2&&p===ctx.opener){for(const r of R)for(const c of R){const h=hand(r,c),base=rv('Open'+p,h),b4=rv(`4Bet${p}vs${ctx.three}`,h),ca=rv(`Call 3Bet${p}vs${ctx.three}`,h);let v=null;if(base<=1e-9)v=0;else if(a==='4bet'){v=b4/base;title=`${p} 4bet all-in vs ${ctx.three}`}else if(a==='call'){v=ca/base;title=`${p} Call 3bet vs ${ctx.three}`}else if(a==='fold'){v=(base-b4-ca)/base;title=`${p} Fold vs ${ctx.three} 3bet`}if(v!==null)values[h]=clamp(v)}}else if(ctx.stage>=3&&p===ctx.three){for(const r of R)for(const c of R){const h=hand(r,c),base=rv(`3Bet${p}vs${ctx.opener}`,h),ca=rv(`Call 4Bet${p}vs${ctx.opener}`,h);let v=null;if(base<=1e-9)v=0;else if(a==='call'){v=ca/base;title=`${p} Call 4bet vs ${ctx.opener}`}else if(a==='fold'){v=(base-ca)/base;title=`${p} Fold vs ${ctx.opener} 4bet`}if(v!==null)values[h]=clamp(v)}}return Object.keys(values).length?{title,values}:null}
function unsupportedText(p,ctx){if(ctx&&ctx.stage===1&&ctx.callers.length)return'すでにCallが入ったmultiway局面のレンジは、この公開データにはありません。';if(ctx&&ctx.stage===2&&p!==ctx.opener)return'cold 4bet / cold call のレンジは、この公開データにはありません。';if(ctx&&ctx.stage>=3&&p!==ctx.three)return'この4betに対するレンジは、この公開データにはありません。';return'このアクション履歴に直接対応する公開レンジデータはありません。'}
function grid(info){if(!info)return'';let html='<div class="custom-range-grid">';for(const r of R)for(const c of R){const h=hand(r,c),v=clamp(info.values[h]||0),pct=Math.round(v*1000)/10;html+=`<div class="custom-range-cell" style="background:linear-gradient(to right,#a9ee61 0%,#a9ee61 ${v*100}%,#39433f ${v*100}%,#39433f 100%)"><div class="custom-hand">${h}</div><div class="custom-pct">${pct}%</div></div>`}return html+'</div>'}
function selectHtml(opts,value,attrs,placeholder,ctx,p){let list=[...opts];if(value&&!opts.some(x=>x[0]===value))list=[[value,`⚠ ${labelFor(value,p,ctx||baseCtx())}`],...list];return`<select class="custom-action-select" ${attrs}><option value="">${placeholder}</option>${list.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`}
function currentDecision(model){if(selected.type==='second')return model.responses[selected.pos]||null;return model.decisions[selected.pos]||null}
function rowHtml(p,model){const d=model.decisions[p],r=model.responses[p];let lines='';if(d&&d.ctx)lines+=selectHtml(d.opts,d.value,`data-first="${p}"`,'アクションを選択',d.ctx,p);else if(first[p])lines+=selectHtml([],first[p],`data-first="${p}"`,'前のプレイヤーを設定',null,p);if(r)lines+=selectHtml(r.opts,r.value,`data-second="${p}"`,`${r.number}回目のアクション`,r.ctx,p);return`<div class="custom-row ${selected.pos===p?'selected':''}"><div class="custom-pos" data-pos="${p}">${p}</div><div class="custom-action-stack">${lines}</div></div>`}
function selectDecision(type,p,model){selected={type,pos:p};const d=type==='second'?model.responses[p]:model.decisions[p];selectedAction=d&&d.value&&d.opts.some(x=>x[0]===d.value)?d.value:(d&&d.opts[0]?d.opts[0][0]:'fold');render()}
function render(){const seq=document.getElementById('customSequence2');if(!seq)return;const model=derive();seq.innerHTML=POS.map(p=>rowHtml(p,model)).join('');seq.querySelectorAll('.custom-pos').forEach(e=>e.onclick=()=>selectDecision(model.responses[e.dataset.pos]?'second':'first',e.dataset.pos,model));seq.querySelectorAll('[data-first]').forEach(e=>{e.onfocus=()=>{selected={type:'first',pos:e.dataset.first}};e.onchange=()=>{first[e.dataset.first]=e.value;selected={type:'first',pos:e.dataset.first};selectedAction=e.value||'fold';render()}});seq.querySelectorAll('[data-second]').forEach(e=>{e.onfocus=()=>{selected={type:'second',pos:e.dataset.second}};e.onchange=()=>{second[e.dataset.second]=e.value;selected={type:'second',pos:e.dataset.second};selectedAction=e.value||'fold';render()}});
 const title=document.getElementById('customTitle2'),context=document.getElementById('customContext2'),tabs=document.getElementById('customActionTabs2'),range=document.getElementById('customRange2'),summary=document.getElementById('customSummary2');title.textContent=`${selected.pos} HAND RANGE`;summary.innerHTML='';const d=currentDecision(model);if(!d||!d.ctx){tabs.innerHTML='';context.textContent='';range.innerHTML='<div class="custom-unsupported">前のプレイヤーのアクションを選択してください</div>';return}if(!d.opts.some(x=>x[0]===selectedAction))selectedAction=d.value&&d.opts.some(x=>x[0]===d.value)?d.value:d.opts[0][0];context.textContent=d.ctx.stage===0?'Unopened pot':d.ctx.stage===1?`${d.ctx.opener} Open ${fmt(d.ctx.openSize)} に対する ${selected.pos} の戦略`:d.ctx.stage===2?`${d.ctx.three} 3bet ${fmt(d.ctx.threeSize)} に対する ${selected.pos} の戦略`:`${d.ctx.four} 4bet all-in に対する ${selected.pos} の戦略`;tabs.innerHTML=d.opts.map(([a,l])=>`<button class="custom-action-btn ${selectedAction===a?'active':''}" data-a="${a}">${l}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedAction=b.dataset.a;render()});const info=rangeInfo(selected.pos,selectedAction,d.ctx);if(info){range.innerHTML=grid(info);summary.innerHTML=`<strong>${info.title}</strong><div class="custom-muted">各セルは、そのハンドでこのアクションを選ぶ頻度です。</div>`}else range.innerHTML=`<div class="custom-unsupported">${unsupportedText(selected.pos,d.ctx)}</div>`}
function reset(){blank();selected={type:'first',pos:'LJ'};selectedAction='open';render()}
function foldAll(){for(const p of POS)first[p]='fold';for(const p of POS)second[p]='';selected={type:'first',pos:'LJ'};selectedAction='fold';render()}
function inject(){const app=document.querySelector('.app'),header=app&&app.querySelector('header');if(!app||!header||document.getElementById('customTab'))return;header.style.justifyContent='space-between';const tabs=document.createElement('div');tabs.className='mode-tabs';tabs.innerHTML='<button class="mode-tab active" id="gameTab2">GAME</button><button class="mode-tab" id="customTab">CUSTOM</button>';header.appendChild(tabs);const gameNodes=[...app.children].filter(x=>x!==header);const wrap=document.createElement('div');wrap.id='gameMode2';for(const n of gameNodes)wrap.appendChild(n);app.appendChild(wrap);const custom=document.createElement('section');custom.id='customMode2';custom.hidden=true;custom.innerHTML='<section class="custom-mode-panel"><div><h2 style="font-size:13px;letter-spacing:.11em;margin:0">CUSTOM MODE</h2><div class="custom-muted">各ポジションの設定は保持されます。選択肢とレンジは、それ以前のアクションから自動計算します。</div></div><div class="custom-grid"><div><div class="custom-sequence" id="customSequence2"></div><div class="custom-control-row"><button class="custom-reset" id="customReset2">リセット</button><button class="custom-reset" id="customFoldAll2">全てフォールド</button></div></div><div><h2 id="customTitle2" style="font-size:13px;letter-spacing:.11em;margin:0">LJ HAND RANGE</h2><div class="custom-muted" id="customContext2"></div><div class="custom-toolbar" id="customActionTabs2"></div><div class="custom-range-wrap" id="customRange2"></div><div class="custom-summary" id="customSummary2"></div></div></div></section>';app.appendChild(custom);document.getElementById('gameTab2').onclick=()=>setMode(false);document.getElementById('customTab').onclick=()=>setMode(true);document.getElementById('customReset2').onclick=reset;document.getElementById('customFoldAll2').onclick=foldAll}
function setMode(custom){document.getElementById('gameMode2').hidden=custom;document.getElementById('customMode2').hidden=!custom;document.getElementById('gameTab2').classList.toggle('active',!custom);document.getElementById('customTab').classList.toggle('active',custom);if(custom)render()}
function boot(){inject();blank();fetch(DATA_URL).then(r=>r.ok?r.json():Promise.reject()).then(x=>{ranges=x;render()}).catch(()=>render())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();