(()=>{'use strict';
const DATA_URL='https://raw.githubusercontent.com/jensbaagaard/poker-practice/main/data/openSourcePokerData/MTT_40_GTO.json';
const POS=['LJ','HJ','CO','BTN','SB','BB'];
const R=['A','K','Q','J','T','9','8','7','6','5','4','3','2'];
let ranges=null,state={LJ:'',HJ:'',CO:'',BTN:'',SB:'',BB:''},selectedPos='LJ',selectedAction='open',selectedHand='AA';
const clamp=v=>Math.max(0,Math.min(1,v));
const rv=(k,h)=>ranges&&ranges[k]?Number(ranges[k][h]||0):0;
function hand(r,c){if(r===c)return r+r;return R.indexOf(r)<R.indexOf(c)?r+c+'s':c+r+'o'}
function before(p){const i=POS.indexOf(p),prev=POS.slice(0,i);return{opener:prev.find(x=>state[x]==='open')||null,three:prev.find(x=>state[x]==='3bet')||null,limped:prev.some(x=>state[x]==='limp')}}
function options(p){const x=before(p);if(x.limped&&!x.opener)return[['fold','Fold'],['limp','Limp'],['open','Open']];if(!x.opener)return[['fold','Fold'],['limp','Limp'],['open','Open']];if(!x.three)return[['fold','Fold'],['call','Call'],['3bet','3bet']];return[['fold','Fold'],['call','Call'],['4bet','4bet all-in']]}
function label(a){return({fold:'Fold',limp:'Limp',open:'Open',call:'Call','3bet':'3bet','4bet':'4bet'})[a]||a}
function rangeInfo(p,a){if(!ranges)return null;const x=before(p),values={};let title='';if(x.limped&&!x.opener)return null;for(const r of R)for(const c of R){const h=hand(r,c);let v=null;if(!x.opener){const o=rv('Open'+p,h),l=rv('Limp'+p,h);if(a==='open'){v=o;title=`${p} Open`}else if(a==='limp'){v=l;title=`${p} Limp`}else if(a==='fold'){v=1-o-l;title=`${p} Fold`}}else if(!x.three){const t=rv(`3Bet${p}vs${x.opener}`,h),cl=rv(`Call${p}vs${x.opener}`,h);if(a==='3bet'){v=t;title=`${p} 3bet vs ${x.opener}`}else if(a==='call'){v=cl;title=`${p} Call vs ${x.opener}`}else if(a==='fold'){v=1-t-cl;title=`${p} Fold vs ${x.opener}`}}if(v!==null)values[h]=clamp(v)}return Object.keys(values).length?{title,values}:null}
function inject(){const app=document.querySelector('.app'),header=app&&app.querySelector('header');if(!app||!header||document.getElementById('customTab'))return;header.style.justifyContent='space-between';const tabs=document.createElement('div');tabs.className='mode-tabs';tabs.innerHTML='<button class="mode-tab active" id="gameTab2">GAME</button><button class="mode-tab" id="customTab">CUSTOM</button>';header.appendChild(tabs);const gameNodes=[...app.children].filter(x=>x!==header);const wrap=document.createElement('div');wrap.id='gameMode2';for(const n of gameNodes)wrap.appendChild(n);app.appendChild(wrap);const custom=document.createElement('section');custom.id='customMode2';custom.hidden=true;custom.innerHTML='<section class="custom-mode-panel"><div><h2 style="font-size:13px;letter-spacing:.11em;margin:0">CUSTOM MODE</h2><div class="custom-muted">LJから順にアクションを指定し、任意のポジション・ハンドのアクション頻度を確認できます。</div></div><div class="custom-grid"><div><div class="custom-sequence" id="customSequence2"></div><button class="custom-reset" id="customReset2">リセット</button></div><div><h2 id="customTitle2" style="font-size:13px;letter-spacing:.11em;margin:0">LJ HAND RANGE</h2><div class="custom-muted" id="customContext2"></div><div class="custom-toolbar" id="customActionTabs2"></div><div class="custom-range-wrap" id="customRange2"></div><div class="custom-summary" id="customSummary2"></div></div></div></section>';app.appendChild(custom);document.getElementById('gameTab2').onclick=()=>setMode(false);document.getElementById('customTab').onclick=()=>setMode(true);document.getElementById('customReset2').onclick=()=>{state={LJ:'',HJ:'',CO:'',BTN:'',SB:'',BB:''};selectedPos='LJ';selectedAction='open';selectedHand='AA';render()};}
function setMode(custom){document.getElementById('gameMode2').hidden=custom;document.getElementById('customMode2').hidden=!custom;document.getElementById('gameTab2').classList.toggle('active',!custom);document.getElementById('customTab').classList.toggle('active',custom);if(custom)render()}
function grid(info){if(!info)return'<div class="custom-unsupported">このアクション履歴に直接対応する公開レンジデータはありません。</div>';let html='<div class="custom-range-grid">';for(const r of R)for(const c of R){const h=hand(r,c),v=clamp(info.values[h]||0),pct=Math.round(v*1000)/10;html+=`<div class="custom-range-cell ${selectedHand===h?'selected':''}" data-hand="${h}" style="background:linear-gradient(to right,#a9ee61 0%,#a9ee61 ${v*100}%,#39433f ${v*100}%,#39433f 100%)"><div class="custom-hand">${h}</div><div class="custom-pct">${pct}%</div></div>`}return html+'</div>'}
function render(){const seq=document.getElementById('customSequence2');if(!seq)return;seq.innerHTML=POS.map((p,i)=>{const enabled=i===0||POS.slice(0,i).every(x=>state[x]);const opts=options(p);return`<div class="custom-row ${selectedPos===p?'selected':''}"><div class="custom-pos" data-pos="${p}">${p}</div><select data-pos="${p}" ${enabled?'':'disabled'}><option value="">アクションを選択</option>${opts.map(([v,l])=>`<option value="${v}" ${state[p]===v?'selected':''}>${l}</option>`).join('')}</select></div>`}).join('');seq.querySelectorAll('.custom-pos').forEach(e=>e.onclick=()=>{selectedPos=e.dataset.pos;const acts=options(selectedPos).map(x=>x[0]);selectedAction=state[selectedPos]&&acts.includes(state[selectedPos])?state[selectedPos]:acts[0];render()});seq.querySelectorAll('select').forEach(e=>e.onchange=()=>{const p=e.dataset.pos,idx=POS.indexOf(p);state[p]=e.value;for(const q of POS.slice(idx+1))state[q]='';selectedPos=p;selectedAction=e.value||options(p)[0][0];render()});const x=before(selectedPos),acts=options(selectedPos).map(x=>x[0]);if(!acts.includes(selectedAction))selectedAction=state[selectedPos]&&acts.includes(state[selectedPos])?state[selectedPos]:acts[0];document.getElementById('customTitle2').textContent=`${selectedPos} HAND RANGE`;document.getElementById('customContext2').textContent=x.opener?`${x.opener} のオープンに対する ${selectedPos} の戦略`:x.limped?'前にLimpがある履歴はこの公開データでは直接対応していません':'Unopened pot';const tabs=document.getElementById('customActionTabs2');tabs.innerHTML=acts.map(a=>`<button class="custom-action-btn ${selectedAction===a?'active':''}" data-a="${a}">${label(a)}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedAction=b.dataset.a;render()});const info=rangeInfo(selectedPos,selectedAction),range=document.getElementById('customRange2');range.innerHTML=grid(info);if(info)range.querySelectorAll('[data-hand]').forEach(e=>e.onclick=()=>{selectedHand=e.dataset.hand;render()});const chips=acts.map(a=>{const i=rangeInfo(selectedPos,a),v=i?i.values[selectedHand]:null;return`<span class="custom-chip">${label(a)} ${v==null?'—':(Math.round(v*1000)/10)+'%'}</span>`}).join('');document.getElementById('customSummary2').innerHTML=`<strong>${selectedPos} · ${selectedHand}</strong><div class="custom-chips">${chips}</div>`}
function boot(){inject();fetch(DATA_URL).then(r=>r.json()).then(x=>{ranges=x;render()}).catch(()=>render())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();